### ISSUE TITLE
Can you provide utils.py?

### ISSUE THREAD

**Issue by Yushu-Li** [pasqualecoscia/MLP-Mixer-CIFAR10#1]
Hello. I have some problems when I run main_cifar10.py.
![image](https://user-images.githubusercontent.com/80386494/119215089-10b9be80-bafe-11eb-9ee1-de005c444a7e.png)
Can you provide utils.py?

**Comment by pasqualecoscia** [comment]
I've added 'utils.py' to the repo.

**Comment by Yushu-Li** [comment]
Thanks
